/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e2e8f0",
        "on-background": "#1e293b",
        "tertiary-fixed": "#ecdcff",
        "background": "#f8fafc",
        "tertiary-container": "#b88eff",
        "error-container": "#ffdad6",
        "inverse-primary": "#a2c9ff",
        "on-primary-fixed-variant": "#004882",
        "surface": "#f9f9ff",
        "error": "#ba1a1a",
        "secondary-fixed": "#83fc89",
        "secondary": "#006d3a",
        "on-primary": "#ffffff",
        "outline-variant": "#cbd5e1",
        "tertiary": "#6b4fa3",
        "surface-container": "#f1f5f9",
        "inverse-on-surface": "#f1f5f9",
        "surface-tint": "#0060aa",
        "primary-fixed": "#d3e4ff",
        "on-tertiary-fixed-variant": "#5a21ab",
        "tertiary-fixed-dim": "#d5bbff",
        "surface-variant": "#e2e8f0",
        "surface-container-highest": "#cbd5e1",
        "on-secondary-fixed": "#002105",
        "on-secondary-container": "#00210a",
        "on-error-container": "#410002",
        "on-primary-fixed": "#001c38",
        "primary": "#0060aa",
        "outline": "#64748b",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f8fafc",
        "surface-bright": "#ffffff",
        "on-tertiary-container": "#270058",
        "surface-dim": "#e2e8f0",
        "primary-container": "#d3e4ff",
        "on-error": "#ffffff",
        "secondary-container": "#93f89d",
        "inverse-surface": "#1e293b",
        "primary-fixed-dim": "#a2c9ff",
        "on-tertiary-fixed": "#270058",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#001c38",
        "on-surface-variant": "#475569",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#1e293b",
        "on-secondary-fixed-variant": "#005317",
        "secondary-fixed-dim": "#67df70"
      },
      spacing: {
        "gutter": "16px",
        "unit": "4px",
        "density-tight": "8px",
        "container-padding": "24px",
      }
    },
  },
  plugins: [],
}
