/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e7e8e9",
        "on-background": "#191c1d",
        "tertiary-fixed": "#dbe4ed",
        "background": "#f8f9fa",
        "tertiary-container": "#6a737b",
        "error-container": "#ffdad6",
        "inverse-primary": "#b3c5ff",
        "on-primary-fixed-variant": "#003fa4",
        "surface": "#f8f9fa",
        "error": "#ba1a1a",
        "secondary-fixed": "#83fc8e",
        "secondary": "#006e25",
        "on-primary": "#ffffff",
        "outline-variant": "#c2c6d8",
        "tertiary": "#525b62",
        "surface-container": "#edeeef",
        "inverse-on-surface": "#f0f1f2",
        "surface-tint": "#0054d6",
        "primary-fixed": "#dae1ff",
        "on-tertiary-fixed-variant": "#3f484f",
        "tertiary-fixed-dim": "#bfc8d0",
        "surface-variant": "#e1e3e4",
        "surface-container-highest": "#e1e3e4",
        "on-secondary-fixed": "#002106",
        "on-secondary-container": "#007327",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#001849",
        "primary": "#0050cb",
        "outline": "#727687",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-bright": "#f8f9fa",
        "on-tertiary-container": "#f4f9ff",
        "surface-dim": "#d9dadb",
        "primary-container": "#0066ff",
        "on-error": "#ffffff",
        "secondary-container": "#80f98b",
        "inverse-surface": "#2e3132",
        "primary-fixed-dim": "#b3c5ff",
        "on-tertiary-fixed": "#141d23",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#f8f7ff",
        "on-surface-variant": "#424656",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1d",
        "on-secondary-fixed-variant": "#005317",
        "secondary-fixed-dim": "#66df75"
      },
      spacing: {
        "gutter": "16px",
        "unit": "4px",
        "density-tight": "8px",
        "container-padding": "24px",
        "header-height": "64px",
      }
    },
  },
  plugins: [],
}
